### ISSUE TITLE
Иерархия подразделений

### ISSUE THREAD

**Issue by Ari100kratov** [Ilya181297/TestTask1#3]
1. Настроить таблицу подразделений для возможности работы с иерархической структурой.
2. Вывести дерево подразделений на форме
3. На форма добавления/редактирования реализовать список с выбором родительского подразделения (выпадающий список наименований)

**Comment by Ilya181297** [comment]
https://github.com/Ilya181297/TestTask1/pull/1

**Comment by Ari100kratov** [comment]
Необходимо поправить замечания и приложить сюда скриншот дерева на форме

**Comment by Ilya181297** [comment]
![image](https://user-images.githubusercontent.com/103198621/167316970-4db8927f-4b96-448d-bb2a-a38c301a44eb.png)
https://github.com/Ilya181297/TestTask1/pull/1

**Comment by Ari100kratov** [comment]
Отгружено в master
