### ISSUE TITLE
Работники

### ISSUE THREAD

**Issue by Ari100kratov** [Ilya181297/TestTask1#4]
1. Добавить новую таблицу, для хранения работников (в соответствии с описанием тестового задания).
2. Вывести таблицу на форму и реализовать возможность CRUD-операций.
3. Фильтровать сотрудников в таблице при выборе подразделения

**Comment by Ilya181297** [comment]
https://github.com/Ilya181297/TestTask1/pull/5

**Comment by Ari100kratov** [comment]
Не совсем корректно реализована фильтрация сотрудников. Доработки тогда будут в следующей задаче, т.к. по сути требование в данной задаче соблюдено.

**Comment by Ari100kratov** [comment]
Отгружено в master
