### ISSUE TITLE
Доработка фильтрации сотрудников и небольшое приведение интерфейса в порядок.

### ISSUE THREAD

**Issue by Ari100kratov** [Ilya181297/TestTask1#6]
В задаче #4 была реализована фильтрация сотрудников при клике по подразделению. 
Замечания:
1. При первом открытии никакое подразделение не выбрано. (Выбирается самое высокоуровневое и первое по порядку)
2. Отсутствует индикатор того, какое подразделение выбрано. Думаю можно запихнуть название подразделения сверху таблицы сотрудников. 
3. При выборе подразделения также должны отображаться сотрудники ВСЕХ дочерних подразделений.
4. Также требуется перевести интерфейс на русский язык

**Comment by Ilya181297** [comment]
https://github.com/Ilya181297/TestTask1/pull/7

**Comment by Ari100kratov** [comment]
Отгружено в master
