### ISSUE TITLE
Сервис для работы с подразделениями и работниками

### ISSUE THREAD

**Issue by Ari100kratov** [Ilya181297/TestTask1#8]
1. Сервис будет дополнительной прослойкой между "контроллерами" и контекстом базы данных.
2. В сервисе необходимо реализовать работу с кэшем

Дополнительные требования:
 - сервис должен быть внедрен в IoC-контейнер.
 - должен содержать все необходимые проверки
 - занимается также преобразованием данных, чтобы была возможность максимально упростить код в "контроллерах".

**Comment by Ilya181297** [comment]
https://github.com/Ilya181297/TestTask1/pull/11

**Comment by Ari100kratov** [comment]
По замечаниям будет отдельная задача.
Залил в master
